### ISSUE TITLE
Memory leak in method FaceLocations

### ISSUE THREAD

**Issue by gloednieuw** [takuya-takeuchi/FaceRecognitionDotNet#53] opened 2019-07-09 12:16 UTC
Hi,

When I run my application within a continuous (camera) stream, eventually the application always runs into an overflow exception. I can see that the memory usage keeps increasing and that this is caused by doing the following method call: faceRecognition.FaceLocations(img, 0, model: Model.Cnn).

Can you please check for memory leaks in this method and fix them? Right now the application is not usable because of this issue. Thanks.

![memory 1](https://user-images.githubusercontent.com/28458322/60887199-0a94fe80-a254-11e9-9fea-470cc5b1b709.PNG)
![memory 2](https://user-images.githubusercontent.com/28458322/60887201-0bc62b80-a254-11e9-8931-6e5fbc8087ce.PNG)

**Comment by atabora1** [comment] 2019-07-10 16:01
I'm running into a similar issue when I attempt looping through a series of images. I eventually run out of memory. Any ideas? I've tried setting the the locations object to null and also disposing the encoding object on each iteration. Code below.

using (var image1 = FaceRecognition.LoadImageFile(strFilePath))
                {

                    var faceLocations = _FaceRecognition.FaceLocations(image1).ToArray();

                    var faceEncodings = _FaceRecognition.FaceEncodings(image1).ToArray();

                  
                    int FaceCounter = 0;

                    foreach (var fencoding in faceEncodings)


                    {

                        var bf = new BinaryFormatter();

                        SqlCommand command = new SqlCommand(commandText, sqlconnS);

                        using (var ms1 = new MemoryStream())
                        {
                            bf.Serialize(ms1, fencoding);
                            ms1.Flush();

                          var  bfArray = ms1.ToArray();
                           
                            command.Parameters.Add("@BIN", SqlDbType.Binary, bfArray.Length).Value = bfArray;

                            rowsAffected = command.ExecuteNonQuery();
                            Console.WriteLine("RowsAffected: {0}", rowsAffected);


                            fencoding.Dispose();
                            
                            ms1.Dispose();
                            Array.Clear(bfArray, 0, bfArray.Length);
                            bfArray = new byte[0];
                            bfArray = null;


                        }

                        command = null;
                        FaceCounter++;
                    }//ends for


                    faceLocations = null;
                    sqlconnS.Close();
                    sqlconnS.Dispose();
                    return rowsAffected;

                    //
                }//ends using

**Comment by takuya-takeuchi** [comment] 2019-07-11 14:19
@gloednieuw @atabora1 
hi, I tried to check memory leak on the sample unit test project .

````
        [TestMethod]
        public void Test()
        {
            for (var count = 0; count < 1000; count++)
                using (var img = FaceRecognition.LoadImageFile(Path.Combine("TestImages", "obama-1080p.jpg")))
                {
                    var detectedFaces = this._FaceRecognition.FaceLocations(img, 0, Model.Cnn).ToArray();
                    foreach (var detectedFace in detectedFaces)
                    {
                        Console.WriteLine(detectedFace);
                    }
                }
        }
````

I run as debug in visual studio.
And I checked diagonosis tool to watch memory usage.
But I was not able to see GC work and rising memory. It works fine.

NOTE: I used FaceRecognitionDotNet and latest version of DlibDotNet.CUDA101 and DlibDotNet.

Could you give the minimum sample project as zip file?

**Comment by gloednieuw** [comment] 2019-07-12 09:23
Hi @takuya-takeuchi ,

I created a minimal sample project which should show the memory leak. The program opens up your webcam and indefinitely sends webcam frames to the face locator method. Be sure to run it on GPU with CUDA.

Program can be downloaded here:
https://we.tl/t-K9CUWCfBe2

Thanks for looking into it!

**Comment by atabora1** [comment] 2019-07-12 14:31
Hi  @takuya-takeuchi
Thanks for including the test examples. I ran them and confirmed that there wasn't a memory leak in the "_FaceRecognition.FaceLocations" call. So I retraced my code and pinpointed the issue. I had the "FaceRecognition.Create" declaration statement within a function. This function was called several times in a loop. This is what caused the memory issue. I resolved the issue by moving it out of the function with the for loop and only declaring it once. This is the code that I moved.

FaceRecognition faceRecognition = null;
            var tempModelDirectory = "Models";
            faceRecognition = FaceRecognition.Create(tempModelDirectory);

**Comment by atabora1** [comment] 2019-07-12 14:34
@takuya-takeuchi ,

Thanks once again for your help. much appreciated.

**Comment by takuya-takeuchi** [comment] 2019-07-12 15:01
@atabora1 
It's my pleasure.
Please don't hesitate to report issue and request here!!

@gloednieuw 
Thank you for publish sample.
I started to check it. Please give me a time.

**Comment by takuya-takeuchi** [comment] 2019-07-12 15:13
@gloednieuw 
Hi, I checked sample.
I have some question.

* You should dispose object which be got from FaceRecognition.LoadImage
* I comment out FRDN code. Then, GC is frequently called and memory usage is rising.
````
		private void ExtractEncodings(byte[] image)
		{
			byte[] imageByte;
			int row, column, size;

			(imageByte, row, column, size) = GetImageFromByteArray(image);

            //using (Image recImage = FaceRecognition.LoadImage(imageByte, row, column, size))
            //{

                //List<Location> locations = faceRecognition.FaceLocations(recImage, 0, model: Model.Cnn).ToList();
            //}
        }
````
* I fount you use OpenCVSharp. OpenCVSharp.Mat has memory leak issue.
** https://github.com/shimat/opencvsharp/issues/559
** https://github.com/shimat/opencvsharp/issues/540

@atabora1 said the issue is resolved.
So could you show me the evidence that FRDN component cause memory leak.

**Comment by gloednieuw** [comment] 2019-07-15 07:25
@takuya-takeuchi thanks for looking into it. You're right in that it was the Image object that was causing the leak. I enclosed the object in a using statement and now everything seems to work fine, so for me the issue is solved. Thanks again!

**Closed** 2019-07-15 07:57 UTC
Labels: bug
